# Generated by Django 5.1.3 on 2024-11-23 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_hour', models.DateTimeField(auto_now_add=True)),
                ('linea', models.CharField(max_length=10)),
                ('hu', models.CharField(max_length=50)),
                ('date_hu', models.CharField(blank=True, max_length=10, null=True)),
                ('material', models.CharField(blank=True, max_length=20, null=True)),
                ('motivo', models.CharField(blank=True, max_length=100, null=True)),
                ('submotivo', models.CharField(blank=True, max_length=100, null=True)),
                ('procedencia', models.CharField(blank=True, max_length=100, null=True)),
                ('escaneo', models.CharField(max_length=200)),
                ('comentarios', models.CharField(blank=True, max_length=100, null=True)),
                ('carril', models.CharField(blank=True, max_length=200, null=True)),
                ('colaborador', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
