# Generated by Django 5.1.3 on 2024-11-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_time', models.DateTimeField(auto_now_add=True)),
                ('Sales', models.CharField(blank=True, max_length=200, null=True)),
                ('Material', models.CharField(blank=True, max_length=100, null=True)),
                ('Presentation', models.CharField(blank=True, max_length=100, null=True)),
                ('Coworker', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
